version: '3.1'

services:

  db:
    image: mysql:8.0.32
    container_name: api_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: admin
    restart: always
    ports:
      - 8080:8080